#
# Blog Settings
#
name: semih.github.io
author: Semih Kırdinli
description: 
url: https://semih.github.io
title: programming basics
subtitle:
gravatar_url: https://secure.gravatar.com/avatar/ba1fd23455b3cbbe3a5020816de402b8
copyright: by Semih Kırdinli
excerpt_separator: "" # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed/
subscribe_rss: https://semih.github.io/rss.xml
email: semihkirdinli@gmail.com

# Github repositories
github_user: semih
github_repo_url: https://github.com/semih/semih.github.io/

# Twitter
twitter_user: semihkirdinli
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: semihkirdinli
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-81569202-1

kramdown:
  hard_wrap: true

#
# Jekyll Settings
#
#permalink: /archive/:year/:month/:day/:title/
permalink: /:categories/:title/
paginate: 10
paginate_path: "page/:num"
category_dir: categories
languages: ["en", "tr"]
language_default: "en"
baseurl:          /

t:
  en:
    about: "about"
    archive: "archive"
    contact: "contact"
    contributors: "contributors"
    url: "/en"
    comments: "comments"
    edit: "edit"
  tr:
    about: "hakkımda"
    archive: "arşiv"
    contact: "iletişim"
    contributors: "katkıda bulun"
    url: "/tr"
    comments: "yorumlar"
    edit: "düzenle"


feed:
  path: rss.xml

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude_from_localizations:
  ["javascript", "images", "css", "Gemfile", "scripts", "LICENSE", "README.md"]
